version: '3.8'

services:
  db:
    image: mongo:7.0.16-rc1-jammy
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand({ ping: 1 })' | mongosh --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  initdb:
    build: .
    container_name: initdb
    command: [ "python", "-m", "app.core.db_helper" ]
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  web:
    build: .
    container_name: web
    restart: always
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
      initdb:
        condition: service_completed_successfully
    env_file:
      - .env

volumes:
  mongo_data:
